// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApd04h_Qvl59S6ZRJ4PJRScHiAA3D8zPc',
    appId: '1:290551666383:web:6797875c410f53859649ba',
    messagingSenderId: '290551666383',
    projectId: 'auth-b01a3',
    authDomain: 'auth-b01a3.firebaseapp.com',
    storageBucket: 'auth-b01a3.firebasestorage.app',
    measurementId: 'G-3M63QGH8TT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd2Skv7SBO0qptfDPPV5BEJNyJ3sJUHxo',
    appId: '1:290551666383:android:55e089a01acff1dd9649ba',
    messagingSenderId: '290551666383',
    projectId: 'auth-b01a3',
    storageBucket: 'auth-b01a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi447U8M8gW-7rqKn3mKJu2B-6GNI8XWk',
    appId: '1:290551666383:ios:fbff969d7fff9e6c9649ba',
    messagingSenderId: '290551666383',
    projectId: 'auth-b01a3',
    storageBucket: 'auth-b01a3.firebasestorage.app',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi447U8M8gW-7rqKn3mKJu2B-6GNI8XWk',
    appId: '1:290551666383:ios:fbff969d7fff9e6c9649ba',
    messagingSenderId: '290551666383',
    projectId: 'auth-b01a3',
    storageBucket: 'auth-b01a3.firebasestorage.app',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApd04h_Qvl59S6ZRJ4PJRScHiAA3D8zPc',
    appId: '1:290551666383:web:e2d67c539787637e9649ba',
    messagingSenderId: '290551666383',
    projectId: 'auth-b01a3',
    authDomain: 'auth-b01a3.firebaseapp.com',
    storageBucket: 'auth-b01a3.firebasestorage.app',
    measurementId: 'G-RZVZSLTKQP',
  );
}
